"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['momu_b5.py']
DATA_FILES = ['clientes_momu.db', 'reportes_momu.db', 'compras_momu.db', 'cotizaciones_momu.db', 'productos_momu.db', 'registros_momu.db', 'tmpCot_momu.db', 'tmpVent_momu.db', 'tmpI1_momu.db', 'tmpI2_momu.db', 'tmpI3_momu.db', 'tmpI4_momu.db', 'tmpI5_momu.db', 'orden_momu.db', 'tmpR1_momu.db', 'tmpR2_momu.db', 'ventas_momu.db']
OPTIONS = {
	'argv_emulation':False,
	'iconfile':'ok_momu_icon.icns'

}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
	py_modules=['modulo_reporte', 'modulo_inventario', 'modulo_registro', 'modulo_venta', 'momu_db_b5']
)
